In [1]:
# Use numpy for 2d arrays

In [23]:
import numpy as np

In [37]:
arr1 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [34]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Inserting rows or columns

In [38]:
arr2 = np.insert(arr1, 1, [[10,11,12]], axis = 1)

In [39]:
# axis = 0 => Row                axis = 1 => Column

In [40]:
arr2

array([[ 1, 10,  2,  3],
       [ 4, 11,  5,  6],
       [ 7, 12,  8,  9]])

In [41]:
arr3 = np.insert(arr2, 0, [[1,2,3,4]], axis = 0)

In [42]:
arr3

array([[ 1,  2,  3,  4],
       [ 1, 10,  2,  3],
       [ 4, 11,  5,  6],
       [ 7, 12,  8,  9]])

In [46]:
# Append based on axis 0 or 1

In [49]:
arr4 = np.append(arr3, [[0,1,2,3]], axis = 0)

In [50]:
arr4

array([[ 1,  2,  3,  4],
       [ 1, 10,  2,  3],
       [ 4, 11,  5,  6],
       [ 7, 12,  8,  9],
       [ 0,  1,  2,  3]])

In [59]:
arr4[2][1]

11

In [ ]:
# Searching an element through traversal

In [63]:
a = 8
for i in range(len(arr4)):
    for j in range(len(arr4[i])):
        if arr4[i][j] == a:
            print("Found at ("+ str(i)+", "+str(j)+")")

Found at (3, 2)


In [64]:
# Deleting a row or column with a given index for the same 

In [65]:
arr4

array([[ 1,  2,  3,  4],
       [ 1, 10,  2,  3],
       [ 4, 11,  5,  6],
       [ 7, 12,  8,  9],
       [ 0,  1,  2,  3]])

In [70]:
arr5 = np.delete(arr4, 0, axis = 0)

In [72]:
arr5

array([[ 1, 10,  2,  3],
       [ 4, 11,  5,  6],
       [ 7, 12,  8,  9],
       [ 0,  1,  2,  3]])